### ISSUE TITLE
incorrect JSON name in checkin entity

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#1]
JSON response has a suspicious name `"$reql_type$"`, here; 
`"location": {
      "$reql_type$": "GEOMETRY",
      "coordinates": [
`

**Comment by Starefossen** [comment]
This is valid JSON and GeoJSON it is just a reference for the RethinkDB geometry datatype which makes it possible to translate from the native RethinkDB data structure to to JSON.

Unless there exists an actual incompatibility with used libraries / tools for the Sjekk UT application I do not see the benefit by using time to add extra logic to remove this from the returned JSON data.

**Comment by hhartz** [comment]
ok, thanks for the update!
