### ISSUE TITLE
provide a 'url' field that can be used for sharing purposes

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#19]
Some people might want to share their checkin. For this purpose we need to have a url to a webpage that proves the user was really there. The URL to this web page should be returned in the JSON-encoded response when creating a checkin, as a field `url`, e.g.;

``` json
{
  "message": "Ok",
  "data": {
    "timestamp": "2016-08-26T07:02:11.522Z",
    "ntb_steder_id": "ed5edf598770a7cf21dd8e87",
    "dnt_user_id": 123456,
    "_id": "a72f5e17af1dcf06c2353d5bd",
    "location": {
      "type": "Point",
      "coordinates": [
        10,
        59
      ]
    },
   "sharing_url":"https://sjekkut.dnt.no/besok/a72f5e17af1dcf06c2353d5bd"
  }
}
```

The page should use e.g. [Facebook Open Graph](https://developers.facebook.com/docs/sharing/best-practices#tags) meta tags to ensure correct title/image/text is set;

**Comment by Starefossen** [comment]
This should be implemented as a virtual property on the Checkin model. This way we can dynamically set the sharing URL for all existing and new checkins.

**Comment by Starefossen** [comment]
Should return `""` (empty string) if not defined.
