### ISSUE TITLE
/steder/{id}/logg returns all checkins

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#2]
expected behavior: only return the authorized user's checkins

**Comment by hhartz** [comment]
@Starefossen actually, perhaps it's reasonable to keep this as is (as long as its anonymized for other users), and instead use (the notImplementedYet) /brukere/:bruker/logg to populate a users' own checkins? This way it would be possible for mobile clients to show that someone else visited it 30 minutes ago etc

**Comment by Starefossen** [comment]
`/steder/{id}/logg` is supposed to return all check ins.
