### ISSUE TITLE
/lister/:id/meldav will delete other lists

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#27]
If you issue multiple commands to meldav (with the same id), will eventually clear `lister` entirely

**Comment by geekus** [comment]
I see that the implementation does not account for trying to leave a list that the user has not joined. Will fix. Testing the relevant code line a little, indicates that it's just the _last_ item that is being removed, and the array is not cleared if containing more than _one_ item.

Have you experienced this behavior with a user that has joined more than one list?

**Comment by hhartz** [comment]
@geekus yes, discovered it by joining two lists, then double-tapping the leave. Will implement disabling the button while a request is in-flight in the meantime

**Comment by geekus** [comment]
Or maybe that's what you mean by eventually. By removing the last item enough times, even users with multiple lists will have all of them removed.

**Comment by geekus** [comment]
Okay, but I'll fix this. You should not have to account for this bug. 😊

**Comment by hhartz** [comment]
well it makes sense to limit the amount of unnecessary traffic in any case ;)

**Comment by geekus** [comment]
Sure, It's obviously a good practice anyway to have a button disabled (also visually for the user to see) while waiting for a response to a request.
