### ISSUE TITLE
404 returned when fetching user profile

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#3]
attempting to fetch all checkins for user on app launch returns 404

e.g. https://sjekkut.app.dnt.no/v1/brukere/194708

**Comment by Starefossen** [comment]
Yes, this is because the user have not yet created a profile in Sjekk UT. However, we could simply return an empty user object if the user have not joined any lists or checked in.

**Comment by hhartz** [comment]
@Starefossen the user has multiple checkins - but has not joined any lists since that's not implemented yet

**Comment by Starefossen** [comment]
A user profile is now properly created whenever a user checks in or joins a list. This endpoint will return 404 if the user have not checked in or joined a list yet. Closing.
