### ISSUE TITLE
Constrain check in radius/time on /steder/{id}/besok

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#4]
it should currently require the user to be within a 200m radius from the place, and should only be possible to check in once pr 24 hours

**Comment by Starefossen** [comment]
This should be implemented as an [Async Custom Validator](http://mongoosejs.com/docs/validation.html#async-custom-validators) on the Checkin model:

1. Fetch sted from Nasjonal Turbase
2. Measure the distance from user's `location` using [node-geoutil](https://github.com/Turistforeningen/node-geoutil)
3. Profit!

**Comment by geekus** [comment]
Merged by PR #42 .
