### ISSUE TITLE
new user times out on /v2/brukere/:id

### ISSUE THREAD

**Issue by hhartz** [Turistforeningen/Verdandi#46]
e.g. `curl -H 'Host: sjekkut.app.dnt.no' -H 'Accept: */*' -H 'User-Agent: SjekkUT/8 CFNetwork/758.5.3 Darwin/15.6.0' -H 'X-User-Id: $(DNT_ID)' -H 'Accept-Language: en-us' -H 'X-User-Token: $(DNT_TOKEN)' --compressed 'https://sjekkut.app.dnt.no/v2/brukere/209639'` times out

**Comment by geekus** [comment]
Is this one still an issue? If that's the case – what defines a _new user_?

**Comment by hhartz** [comment]
no longer an issue, this endpoint returns `404`
