### ISSUE TITLE
Commit message format

### ISSUE THREAD

**Issue by Starefossen** [Turistforeningen/Verdandi#49]
Just a quick reminder. If you go to the [release page](https://github.com/Turistforeningen/Verdandi/releases) there are a few things I would like to point out:

1. use consistent names for scopes. Mixing upper and lower case does not only look odd but also creates separate entries for their respective release.

2. use good commit messages that gives meaning without having to read the whole message. Try to avoid unnecessary abbreviations.

3. using specific scopes, avoid using `project` as a catch all. Use `server` for server related changed or `api` for general API related changes.

This is meant as a friendly advise from one coder to another. Feel free to close this issue when you feel like it 🙃🚀🖖🏼

**Comment by geekus** [comment]
1. Upper and lower case mix was to differentiate between model (Checkpoint) and endpoint (checkpoint), but this is obviously not obvious.
2. Yes
3. 👍
